services: docker
env:
  global:
  - GCP_PROJECT_ID=your-project-id
  - IMAGE=gcr.io/your-project-id/example-app
  - CLOUD_RUN_SERVICE=example-app
  - CLOUD_RUN_REGION=us-central1
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1 # prevent gcloud from prompting, see https://cloud.google.com/sdk/gcloud/reference/#--quiet
before_install:
- echo REMOVE_ME # replace with the openssl command from "travis encrypt-file"
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=google-key.json # login, for service accounts
- gcloud auth configure-docker    # login to gcr, to enable "docker push"
- gcloud config set project "${GCP_PROJECT_ID}"
- gcloud components install
install: true # no-op
script:
- |
  set -ex;
  docker build -t "${IMAGE}:${TRAVIS_COMMIT}" ./src && \
  docker push "${IMAGE}:${TRAVIS_COMMIT}" && \
  gcloud run deploy "${CLOUD_RUN_SERVICE}" \
    --image="${IMAGE}:${TRAVIS_COMMIT}" \
    --platform=managed \
    --region="${CLOUD_RUN_REGION}" \
    --allow-unauthenticated;
  set +x
